### ISSUE TITLE
Single quotes around content and other parameters are replaced with 

### ISSUE THREAD

**Issue by noumaan** [mmatthews1981/kill-in-feed#1]
Single quotes in the function for second shortcode are replaced by ‘ on line 21 and 25. Which means addtofeed shortcode does not work. The issue is also present in WordPress repository.

**Comment by mmatthews1981** [comment]
Ok, let me check it out.

**Comment by mmatthews1981** [comment]
The smartquotes have been replaced, and github and WordPress repositories updated. Thanks for letting me know!
